#!/bin/bash --login
#$ -cwd 
#$ -N nek5000_job1 
#$ -pe amd.pe 4
#$ -l short

chmod -R u+x *
module load mpi/gcc/openmpi/4.1.6

echo "turbPipe" > SESSION.NAME
echo "/mnt/iusers01/fse-ugpgt01/mace01/t62601ej/scratch/KTH_Framework/Examples/pipe_STAT/" >> SESSION.NAME

mpirun -np 4 ./nek5000 >> logfile
